name: org_timeviz

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.12
  - pytest
  - pytest-cov
  - ruff
  - mypy
  - pydantic>=2.11
  - pyyaml>=6.0
  - matplotlib>=3.8
  - plotly>=6.0
  - pip
  - pip:
      - types-PyYAML
