name: org_timeviz

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.12
  - pylint
  - pytest
  - pytest-cov
  - black
  - isort
  - mypy
  - pydantic>=2.11
  - pyyaml>=6.0
  - matplotlib>=3.8
  - pip
  - pip:
      - types-PyYAML
